/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import * as b64$ from "../lib/base64.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeBodyForm as encodeBodyForm$,
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as z from "zod";

export enum CreateUserFormAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum CreateUserJsonAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum CreateUserRawAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum CreateUsersWithListInputAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum GetUserByNameAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum LoginUserAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export class UserSDK extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Create user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async createUserForm(
        request?: models.User | undefined,
        options?: RequestOptions & { acceptHeaderOverride?: CreateUserFormAcceptEnum }
    ): Promise<models.CreateUserFormResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.User$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ = Object.entries(payload$ || {})
            .map(([k, v]) => {
                return encodeBodyForm$(k, v, { charEncoding: "percent" });
            })
            .join("&");

        const path$ = this.templateURLComponent("/user")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/x-www-form-urlencoded",
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "createUser_form",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.CreateUserFormResponse>()
            .void("2XX", models.CreateUserFormResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", models.CreateUserFormResponse$inboundSchema, { key: "User" })
            .bytes("default", models.CreateUserFormResponse$inboundSchema, {
                ctype: "application/xml",
                key: "Body",
            })
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Create user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async createUserJson(
        request?: models.User | undefined,
        options?: RequestOptions & { acceptHeaderOverride?: CreateUserJsonAcceptEnum }
    ): Promise<models.CreateUserJsonResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.User$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/user")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "createUser_json",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.CreateUserJsonResponse>()
            .void("2XX", models.CreateUserJsonResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", models.CreateUserJsonResponse$inboundSchema, { key: "User" })
            .bytes("default", models.CreateUserJsonResponse$inboundSchema, {
                ctype: "application/xml",
                key: "Body",
            })
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Create user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async createUserRaw(
        request?: Uint8Array | string | undefined,
        options?: RequestOptions & { acceptHeaderOverride?: CreateUserRawAcceptEnum }
    ): Promise<models.CreateUserRawResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => b64$.zodOutbound.optional().parse(value$),
            "Input validation failed"
        );
        const body$ = payload$ === undefined ? null : payload$;

        const path$ = this.templateURLComponent("/user")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/xml",
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "createUser_raw",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.CreateUserRawResponse>()
            .void("2XX", models.CreateUserRawResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", models.CreateUserRawResponse$inboundSchema, { key: "User" })
            .bytes("default", models.CreateUserRawResponse$inboundSchema, {
                ctype: "application/xml",
                key: "Body",
            })
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Creates list of users with given input array
     *
     * @remarks
     * Creates list of users with given input array
     */
    async createUsersWithListInput(
        request?: Array<models.User> | undefined,
        options?: RequestOptions & { acceptHeaderOverride?: CreateUsersWithListInputAcceptEnum }
    ): Promise<models.CreateUsersWithListInputResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => z.array(models.User$outboundSchema).optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/user/createWithList")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "createUsersWithListInput",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.CreateUsersWithListInputResponse>()
            .json(200, models.CreateUsersWithListInputResponse$inboundSchema, { key: "User" })
            .bytes(200, models.CreateUsersWithListInputResponse$inboundSchema, {
                ctype: "application/xml",
                key: "Body",
            })
            .fail(["4XX", "5XX"])
            .void("default", models.CreateUsersWithListInputResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Delete user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async deleteUser(
        request: models.DeleteUserRequest,
        options?: RequestOptions
    ): Promise<models.DeleteUserResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.DeleteUserRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            username: encodeSimple$("username", payload$.username, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/user/{username}")(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: "*/*",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "deleteUser",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["400", "404", "4XX", "5XX"],
        });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.DeleteUserResponse>()
            .fail([400, 404, "4XX", "5XX"])
            .void("2XX", models.DeleteUserResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Get user by user name
     */
    async getUserByName(
        request: models.GetUserByNameRequest,
        options?: RequestOptions & { acceptHeaderOverride?: GetUserByNameAcceptEnum }
    ): Promise<models.GetUserByNameResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.GetUserByNameRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            username: encodeSimple$("username", payload$.username, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/user/{username}")(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "getUserByName",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["400", "404", "4XX", "5XX"],
        });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.GetUserByNameResponse>()
            .json(200, models.GetUserByNameResponse$inboundSchema, { key: "User" })
            .bytes(200, models.GetUserByNameResponse$inboundSchema, {
                ctype: "application/xml",
                key: "Body",
            })
            .fail([400, 404, "4XX", "5XX"])
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Logs user into the system
     */
    async loginUser(
        request: models.LoginUserRequest,
        options?: RequestOptions & { acceptHeaderOverride?: LoginUserAcceptEnum }
    ): Promise<models.LoginUserResponse> {
        const input$ = typeof request === "undefined" ? {} : request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.LoginUserRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/user/login")();

        const query$ = encodeFormQuery$({
            password: payload$.password,
            username: payload$.username,
        });

        const headers$ = new Headers({
            Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "loginUser",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["400", "4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.LoginUserResponse>()
            .json(200, models.LoginUserResponse$inboundSchema, { hdrs: true, key: "string" })
            .text(200, models.LoginUserResponse$inboundSchema, {
                ctype: "application/xml",
                hdrs: true,
                key: "res",
            })
            .fail([400, "4XX", "5XX"])
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Logs out current logged in user session
     */
    async logoutUser(options?: RequestOptions): Promise<models.LogoutUserResponse> {
        const path$ = this.templateURLComponent("/user/logout")();

        const query$ = "";

        const headers$ = new Headers({
            Accept: "*/*",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "logoutUser",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.LogoutUserResponse>()
            .fail(["4XX", "5XX"])
            .void(["2XX", "default"], models.LogoutUserResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Update user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async updateUserForm(
        request: models.UpdateUserFormRequest,
        options?: RequestOptions
    ): Promise<models.UpdateUserFormResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.UpdateUserFormRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = Object.entries(payload$.User || {})
            .map(([k, v]) => {
                return encodeBodyForm$(k, v, { charEncoding: "percent" });
            })
            .join("&");

        const pathParams$ = {
            username: encodeSimple$("username", payload$.username, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/user/{username}")(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/x-www-form-urlencoded",
            Accept: "*/*",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "updateUser_form",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.UpdateUserFormResponse>()
            .fail(["4XX", "5XX"])
            .void(["2XX", "default"], models.UpdateUserFormResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Update user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async updateUserJson(
        request: models.UpdateUserJsonRequest,
        options?: RequestOptions
    ): Promise<models.UpdateUserJsonResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.UpdateUserJsonRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.User, { explode: true });

        const pathParams$ = {
            username: encodeSimple$("username", payload$.username, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/user/{username}")(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "*/*",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "updateUser_json",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.UpdateUserJsonResponse>()
            .fail(["4XX", "5XX"])
            .void(["2XX", "default"], models.UpdateUserJsonResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Update user
     *
     * @remarks
     * This can only be done by the logged in user.
     */
    async updateUserRaw(
        request: models.UpdateUserRawRequest,
        options?: RequestOptions
    ): Promise<models.UpdateUserRawResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.UpdateUserRawRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = payload$.RequestBody;

        const pathParams$ = {
            username: encodeSimple$("username", payload$.username, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/user/{username}")(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/xml",
            Accept: "*/*",
        });

        let security$;
        if (typeof this.options$.petstoreAuth === "function") {
            security$ = { petstoreAuth: await this.options$.petstoreAuth() };
        } else if (this.options$.petstoreAuth) {
            security$ = { petstoreAuth: this.options$.petstoreAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "updateUser_raw",
            oAuth2Scopes: [],
            securitySource: this.options$.petstoreAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, { context, errorCodes: ["4XX", "5XX"] });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<models.UpdateUserRawResponse>()
            .fail(["4XX", "5XX"])
            .void(["2XX", "default"], models.UpdateUserRawResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }
}
