/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Category = {
    id?: number | undefined;
    name?: string | undefined;
};

/** @internal */
export const Category$inboundSchema: z.ZodType<Category, z.ZodTypeDef, unknown> = z.object({
    id: z.number().int().optional(),
    name: z.string().optional(),
});

/** @internal */
export type Category$Outbound = {
    id?: number | undefined;
    name?: string | undefined;
};

/** @internal */
export const Category$outboundSchema: z.ZodType<Category$Outbound, z.ZodTypeDef, Category> =
    z.object({
        id: z.number().int().optional(),
        name: z.string().optional(),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Category$ {
    /** @deprecated use `Category$inboundSchema` instead. */
    export const inboundSchema = Category$inboundSchema;
    /** @deprecated use `Category$outboundSchema` instead. */
    export const outboundSchema = Category$outboundSchema;
    /** @deprecated use `Category$Outbound` instead. */
    export type Outbound = Category$Outbound;
}
