/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { User, User$inboundSchema, User$Outbound, User$outboundSchema } from "./user.js";
import * as z from "zod";

export type CreateUsersWithListInputResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful operation
     */
    user?: User | undefined;
};

/** @internal */
export const CreateUsersWithListInputResponse$inboundSchema: z.ZodType<
    CreateUsersWithListInputResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        User: User$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            Body: "body",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
            User: "user",
        });
    });

/** @internal */
export type CreateUsersWithListInputResponse$Outbound = {
    Body?: Uint8Array | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    User?: User$Outbound | undefined;
};

/** @internal */
export const CreateUsersWithListInputResponse$outboundSchema: z.ZodType<
    CreateUsersWithListInputResponse$Outbound,
    z.ZodTypeDef,
    CreateUsersWithListInputResponse
> = z
    .object({
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        user: User$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            body: "Body",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
            user: "User",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUsersWithListInputResponse$ {
    /** @deprecated use `CreateUsersWithListInputResponse$inboundSchema` instead. */
    export const inboundSchema = CreateUsersWithListInputResponse$inboundSchema;
    /** @deprecated use `CreateUsersWithListInputResponse$outboundSchema` instead. */
    export const outboundSchema = CreateUsersWithListInputResponse$outboundSchema;
    /** @deprecated use `CreateUsersWithListInputResponse$Outbound` instead. */
    export type Outbound = CreateUsersWithListInputResponse$Outbound;
}
