/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeletePetRequest = {
    apiKey?: string | undefined;
    /**
     * Pet id to delete
     */
    petId: number;
};

export type DeletePetResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeletePetRequest$ {
    export const inboundSchema: z.ZodType<DeletePetRequest, z.ZodTypeDef, unknown> = z
        .object({
            api_key: z.string().optional(),
            petId: z.number().int(),
        })
        .transform((v) => {
            return {
                ...(v.api_key === undefined ? null : { apiKey: v.api_key }),
                petId: v.petId,
            };
        });

    export type Outbound = {
        api_key?: string | undefined;
        petId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeletePetRequest> = z
        .object({
            apiKey: z.string().optional(),
            petId: z.number().int(),
        })
        .transform((v) => {
            return {
                ...(v.apiKey === undefined ? null : { api_key: v.apiKey }),
                petId: v.petId,
            };
        });
}

/** @internal */
export namespace DeletePetResponse$ {
    export const inboundSchema: z.ZodType<DeletePetResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeletePetResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
