/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type DeletePetRequest = {
    apiKey?: string | undefined;
    /**
     * Pet id to delete
     */
    petId: number;
};

export type DeletePetResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const DeletePetRequest$inboundSchema: z.ZodType<DeletePetRequest, z.ZodTypeDef, unknown> = z
    .object({
        api_key: z.string().optional(),
        petId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            api_key: "apiKey",
        });
    });

/** @internal */
export type DeletePetRequest$Outbound = {
    api_key?: string | undefined;
    petId: number;
};

/** @internal */
export const DeletePetRequest$outboundSchema: z.ZodType<
    DeletePetRequest$Outbound,
    z.ZodTypeDef,
    DeletePetRequest
> = z
    .object({
        apiKey: z.string().optional(),
        petId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            apiKey: "api_key",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePetRequest$ {
    /** @deprecated use `DeletePetRequest$inboundSchema` instead. */
    export const inboundSchema = DeletePetRequest$inboundSchema;
    /** @deprecated use `DeletePetRequest$outboundSchema` instead. */
    export const outboundSchema = DeletePetRequest$outboundSchema;
    /** @deprecated use `DeletePetRequest$Outbound` instead. */
    export type Outbound = DeletePetRequest$Outbound;
}

/** @internal */
export const DeletePetResponse$inboundSchema: z.ZodType<DeletePetResponse, z.ZodTypeDef, unknown> =
    z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

/** @internal */
export type DeletePetResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const DeletePetResponse$outboundSchema: z.ZodType<
    DeletePetResponse$Outbound,
    z.ZodTypeDef,
    DeletePetResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePetResponse$ {
    /** @deprecated use `DeletePetResponse$inboundSchema` instead. */
    export const inboundSchema = DeletePetResponse$inboundSchema;
    /** @deprecated use `DeletePetResponse$outboundSchema` instead. */
    export const outboundSchema = DeletePetResponse$outboundSchema;
    /** @deprecated use `DeletePetResponse$Outbound` instead. */
    export type Outbound = DeletePetResponse$Outbound;
}
