/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteUserRequest = {
    /**
     * The name that needs to be deleted
     */
    username: string;
};

export type DeleteUserResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteUserRequest$ {
    export const inboundSchema: z.ZodType<DeleteUserRequest, z.ZodTypeDef, unknown> = z
        .object({
            username: z.string(),
        })
        .transform((v) => {
            return {
                username: v.username,
            };
        });

    export type Outbound = {
        username: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteUserRequest> = z
        .object({
            username: z.string(),
        })
        .transform((v) => {
            return {
                username: v.username,
            };
        });
}

/** @internal */
export namespace DeleteUserResponse$ {
    export const inboundSchema: z.ZodType<DeleteUserResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteUserResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
