/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type DeleteUserRequest = {
    /**
     * The name that needs to be deleted
     */
    username: string;
};

export type DeleteUserResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const DeleteUserRequest$inboundSchema: z.ZodType<DeleteUserRequest, z.ZodTypeDef, unknown> =
    z.object({
        username: z.string(),
    });

/** @internal */
export type DeleteUserRequest$Outbound = {
    username: string;
};

/** @internal */
export const DeleteUserRequest$outboundSchema: z.ZodType<
    DeleteUserRequest$Outbound,
    z.ZodTypeDef,
    DeleteUserRequest
> = z.object({
    username: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserRequest$ {
    /** @deprecated use `DeleteUserRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteUserRequest$inboundSchema;
    /** @deprecated use `DeleteUserRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteUserRequest$outboundSchema;
    /** @deprecated use `DeleteUserRequest$Outbound` instead. */
    export type Outbound = DeleteUserRequest$Outbound;
}

/** @internal */
export const DeleteUserResponse$inboundSchema: z.ZodType<
    DeleteUserResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type DeleteUserResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const DeleteUserResponse$outboundSchema: z.ZodType<
    DeleteUserResponse$Outbound,
    z.ZodTypeDef,
    DeleteUserResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUserResponse$ {
    /** @deprecated use `DeleteUserResponse$inboundSchema` instead. */
    export const inboundSchema = DeleteUserResponse$inboundSchema;
    /** @deprecated use `DeleteUserResponse$outboundSchema` instead. */
    export const outboundSchema = DeleteUserResponse$outboundSchema;
    /** @deprecated use `DeleteUserResponse$Outbound` instead. */
    export type Outbound = DeleteUserResponse$Outbound;
}
