/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteOrderRequest = {
    /**
     * ID of the order that needs to be deleted
     */
    orderId: number;
};

export type DeleteOrderResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteOrderRequest$ {
    export const inboundSchema: z.ZodType<DeleteOrderRequest, z.ZodTypeDef, unknown> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });

    export type Outbound = {
        orderId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteOrderRequest> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });
}

/** @internal */
export namespace DeleteOrderResponse$ {
    export const inboundSchema: z.ZodType<DeleteOrderResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteOrderResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
