/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type DeleteOrderRequest = {
    /**
     * ID of the order that needs to be deleted
     */
    orderId: number;
};

export type DeleteOrderResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const DeleteOrderRequest$inboundSchema: z.ZodType<
    DeleteOrderRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    orderId: z.number().int(),
});

/** @internal */
export type DeleteOrderRequest$Outbound = {
    orderId: number;
};

/** @internal */
export const DeleteOrderRequest$outboundSchema: z.ZodType<
    DeleteOrderRequest$Outbound,
    z.ZodTypeDef,
    DeleteOrderRequest
> = z.object({
    orderId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOrderRequest$ {
    /** @deprecated use `DeleteOrderRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteOrderRequest$inboundSchema;
    /** @deprecated use `DeleteOrderRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteOrderRequest$outboundSchema;
    /** @deprecated use `DeleteOrderRequest$Outbound` instead. */
    export type Outbound = DeleteOrderRequest$Outbound;
}

/** @internal */
export const DeleteOrderResponse$inboundSchema: z.ZodType<
    DeleteOrderResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type DeleteOrderResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const DeleteOrderResponse$outboundSchema: z.ZodType<
    DeleteOrderResponse$Outbound,
    z.ZodTypeDef,
    DeleteOrderResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOrderResponse$ {
    /** @deprecated use `DeleteOrderResponse$inboundSchema` instead. */
    export const inboundSchema = DeleteOrderResponse$inboundSchema;
    /** @deprecated use `DeleteOrderResponse$outboundSchema` instead. */
    export const outboundSchema = DeleteOrderResponse$outboundSchema;
    /** @deprecated use `DeleteOrderResponse$Outbound` instead. */
    export type Outbound = DeleteOrderResponse$Outbound;
}
