/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { Pet, Pet$inboundSchema, Pet$Outbound, Pet$outboundSchema } from "./pet.js";
import * as z from "zod";

/**
 * Status values that need to be considered for filter
 */
export enum QueryParamStatus {
    Available = "available",
    Pending = "pending",
    Sold = "sold",
}

export type FindPetsByStatusRequest = {
    /**
     * Status values that need to be considered for filter
     */
    status?: QueryParamStatus | undefined;
};

export type FindPetsByStatusResponse = {
    /**
     * successful operation
     */
    twoHundredApplicationJsonClasses?: Array<Pet> | undefined;
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const QueryParamStatus$inboundSchema: z.ZodNativeEnum<typeof QueryParamStatus> =
    z.nativeEnum(QueryParamStatus);

/** @internal */
export const QueryParamStatus$outboundSchema: z.ZodNativeEnum<typeof QueryParamStatus> =
    QueryParamStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryParamStatus$ {
    /** @deprecated use `QueryParamStatus$inboundSchema` instead. */
    export const inboundSchema = QueryParamStatus$inboundSchema;
    /** @deprecated use `QueryParamStatus$outboundSchema` instead. */
    export const outboundSchema = QueryParamStatus$outboundSchema;
}

/** @internal */
export const FindPetsByStatusRequest$inboundSchema: z.ZodType<
    FindPetsByStatusRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    status: QueryParamStatus$inboundSchema.default(QueryParamStatus.Available),
});

/** @internal */
export type FindPetsByStatusRequest$Outbound = {
    status: string;
};

/** @internal */
export const FindPetsByStatusRequest$outboundSchema: z.ZodType<
    FindPetsByStatusRequest$Outbound,
    z.ZodTypeDef,
    FindPetsByStatusRequest
> = z.object({
    status: QueryParamStatus$outboundSchema.default(QueryParamStatus.Available),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByStatusRequest$ {
    /** @deprecated use `FindPetsByStatusRequest$inboundSchema` instead. */
    export const inboundSchema = FindPetsByStatusRequest$inboundSchema;
    /** @deprecated use `FindPetsByStatusRequest$outboundSchema` instead. */
    export const outboundSchema = FindPetsByStatusRequest$outboundSchema;
    /** @deprecated use `FindPetsByStatusRequest$Outbound` instead. */
    export type Outbound = FindPetsByStatusRequest$Outbound;
}

/** @internal */
export const FindPetsByStatusResponse$inboundSchema: z.ZodType<
    FindPetsByStatusResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "200_application/json_classes": z.array(Pet$inboundSchema).optional(),
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            "200_application/json_classes": "twoHundredApplicationJsonClasses",
            Body: "body",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type FindPetsByStatusResponse$Outbound = {
    "200_application/json_classes"?: Array<Pet$Outbound> | undefined;
    Body?: Uint8Array | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const FindPetsByStatusResponse$outboundSchema: z.ZodType<
    FindPetsByStatusResponse$Outbound,
    z.ZodTypeDef,
    FindPetsByStatusResponse
> = z
    .object({
        twoHundredApplicationJsonClasses: z.array(Pet$outboundSchema).optional(),
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            twoHundredApplicationJsonClasses: "200_application/json_classes",
            body: "Body",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByStatusResponse$ {
    /** @deprecated use `FindPetsByStatusResponse$inboundSchema` instead. */
    export const inboundSchema = FindPetsByStatusResponse$inboundSchema;
    /** @deprecated use `FindPetsByStatusResponse$outboundSchema` instead. */
    export const outboundSchema = FindPetsByStatusResponse$outboundSchema;
    /** @deprecated use `FindPetsByStatusResponse$Outbound` instead. */
    export type Outbound = FindPetsByStatusResponse$Outbound;
}
