/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64";
import { Pet, Pet$ } from "./pet";
import * as z from "zod";

export type FindPetsByTagsRequest = {
    /**
     * Tags to filter by
     */
    tags?: Array<string> | undefined;
};

export type FindPetsByTagsResponse = {
    /**
     * successful operation
     */
    twoHundredApplicationJsonClasses?: Array<Pet> | undefined;
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace FindPetsByTagsRequest$ {
    export const inboundSchema: z.ZodType<FindPetsByTagsRequest, z.ZodTypeDef, unknown> = z
        .object({
            tags: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });

    export type Outbound = {
        tags?: Array<string> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FindPetsByTagsRequest> = z
        .object({
            tags: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });
}

/** @internal */
export namespace FindPetsByTagsResponse$ {
    export const inboundSchema: z.ZodType<FindPetsByTagsResponse, z.ZodTypeDef, unknown> = z
        .object({
            "200_application/json_classes": z.array(Pet$.inboundSchema).optional(),
            Body: b64$.zodInbound.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v["200_application/json_classes"] === undefined
                    ? null
                    : { twoHundredApplicationJsonClasses: v["200_application/json_classes"] }),
                ...(v.Body === undefined ? null : { body: v.Body }),
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        "200_application/json_classes"?: Array<Pet$.Outbound> | undefined;
        Body?: Uint8Array | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FindPetsByTagsResponse> = z
        .object({
            twoHundredApplicationJsonClasses: z.array(Pet$.outboundSchema).optional(),
            body: b64$.zodOutbound.optional(),
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.twoHundredApplicationJsonClasses === undefined
                    ? null
                    : { "200_application/json_classes": v.twoHundredApplicationJsonClasses }),
                ...(v.body === undefined ? null : { Body: v.body }),
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
