/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { Pet, Pet$inboundSchema, Pet$Outbound, Pet$outboundSchema } from "./pet.js";
import * as z from "zod";

export type FindPetsByTagsRequest = {
    /**
     * Tags to filter by
     */
    tags?: Array<string> | undefined;
};

export type FindPetsByTagsResponse = {
    /**
     * successful operation
     */
    twoHundredApplicationJsonClasses?: Array<Pet> | undefined;
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const FindPetsByTagsRequest$inboundSchema: z.ZodType<
    FindPetsByTagsRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    tags: z.array(z.string()).optional(),
});

/** @internal */
export type FindPetsByTagsRequest$Outbound = {
    tags?: Array<string> | undefined;
};

/** @internal */
export const FindPetsByTagsRequest$outboundSchema: z.ZodType<
    FindPetsByTagsRequest$Outbound,
    z.ZodTypeDef,
    FindPetsByTagsRequest
> = z.object({
    tags: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByTagsRequest$ {
    /** @deprecated use `FindPetsByTagsRequest$inboundSchema` instead. */
    export const inboundSchema = FindPetsByTagsRequest$inboundSchema;
    /** @deprecated use `FindPetsByTagsRequest$outboundSchema` instead. */
    export const outboundSchema = FindPetsByTagsRequest$outboundSchema;
    /** @deprecated use `FindPetsByTagsRequest$Outbound` instead. */
    export type Outbound = FindPetsByTagsRequest$Outbound;
}

/** @internal */
export const FindPetsByTagsResponse$inboundSchema: z.ZodType<
    FindPetsByTagsResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "200_application/json_classes": z.array(Pet$inboundSchema).optional(),
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            "200_application/json_classes": "twoHundredApplicationJsonClasses",
            Body: "body",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type FindPetsByTagsResponse$Outbound = {
    "200_application/json_classes"?: Array<Pet$Outbound> | undefined;
    Body?: Uint8Array | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const FindPetsByTagsResponse$outboundSchema: z.ZodType<
    FindPetsByTagsResponse$Outbound,
    z.ZodTypeDef,
    FindPetsByTagsResponse
> = z
    .object({
        twoHundredApplicationJsonClasses: z.array(Pet$outboundSchema).optional(),
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            twoHundredApplicationJsonClasses: "200_application/json_classes",
            body: "Body",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByTagsResponse$ {
    /** @deprecated use `FindPetsByTagsResponse$inboundSchema` instead. */
    export const inboundSchema = FindPetsByTagsResponse$inboundSchema;
    /** @deprecated use `FindPetsByTagsResponse$outboundSchema` instead. */
    export const outboundSchema = FindPetsByTagsResponse$outboundSchema;
    /** @deprecated use `FindPetsByTagsResponse$Outbound` instead. */
    export type Outbound = FindPetsByTagsResponse$Outbound;
}
