/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type GetInventorySecurity = {
    apiKey: string;
};

export type GetInventoryResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * successful operation
     */
    object?: { [k: string]: number } | undefined;
};

/** @internal */
export const GetInventorySecurity$inboundSchema: z.ZodType<
    GetInventorySecurity,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        api_key: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            api_key: "apiKey",
        });
    });

/** @internal */
export type GetInventorySecurity$Outbound = {
    api_key: string;
};

/** @internal */
export const GetInventorySecurity$outboundSchema: z.ZodType<
    GetInventorySecurity$Outbound,
    z.ZodTypeDef,
    GetInventorySecurity
> = z
    .object({
        apiKey: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            apiKey: "api_key",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInventorySecurity$ {
    /** @deprecated use `GetInventorySecurity$inboundSchema` instead. */
    export const inboundSchema = GetInventorySecurity$inboundSchema;
    /** @deprecated use `GetInventorySecurity$outboundSchema` instead. */
    export const outboundSchema = GetInventorySecurity$outboundSchema;
    /** @deprecated use `GetInventorySecurity$Outbound` instead. */
    export type Outbound = GetInventorySecurity$Outbound;
}

/** @internal */
export const GetInventoryResponse$inboundSchema: z.ZodType<
    GetInventoryResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        object: z.record(z.number().int()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetInventoryResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    object?: { [k: string]: number } | undefined;
};

/** @internal */
export const GetInventoryResponse$outboundSchema: z.ZodType<
    GetInventoryResponse$Outbound,
    z.ZodTypeDef,
    GetInventoryResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        object: z.record(z.number().int()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInventoryResponse$ {
    /** @deprecated use `GetInventoryResponse$inboundSchema` instead. */
    export const inboundSchema = GetInventoryResponse$inboundSchema;
    /** @deprecated use `GetInventoryResponse$outboundSchema` instead. */
    export const outboundSchema = GetInventoryResponse$outboundSchema;
    /** @deprecated use `GetInventoryResponse$Outbound` instead. */
    export type Outbound = GetInventoryResponse$Outbound;
}
