/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { Order, Order$inboundSchema, Order$Outbound, Order$outboundSchema } from "./order.js";
import * as z from "zod";

export type GetOrderByIdRequest = {
    /**
     * ID of order that needs to be fetched
     */
    orderId: number;
};

export type GetOrderByIdResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    order?: Order | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const GetOrderByIdRequest$inboundSchema: z.ZodType<
    GetOrderByIdRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    orderId: z.number().int(),
});

/** @internal */
export type GetOrderByIdRequest$Outbound = {
    orderId: number;
};

/** @internal */
export const GetOrderByIdRequest$outboundSchema: z.ZodType<
    GetOrderByIdRequest$Outbound,
    z.ZodTypeDef,
    GetOrderByIdRequest
> = z.object({
    orderId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdRequest$ {
    /** @deprecated use `GetOrderByIdRequest$inboundSchema` instead. */
    export const inboundSchema = GetOrderByIdRequest$inboundSchema;
    /** @deprecated use `GetOrderByIdRequest$outboundSchema` instead. */
    export const outboundSchema = GetOrderByIdRequest$outboundSchema;
    /** @deprecated use `GetOrderByIdRequest$Outbound` instead. */
    export type Outbound = GetOrderByIdRequest$Outbound;
}

/** @internal */
export const GetOrderByIdResponse$inboundSchema: z.ZodType<
    GetOrderByIdResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        Order: Order$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            Body: "body",
            ContentType: "contentType",
            Order: "order",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetOrderByIdResponse$Outbound = {
    Body?: Uint8Array | undefined;
    ContentType: string;
    Order?: Order$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const GetOrderByIdResponse$outboundSchema: z.ZodType<
    GetOrderByIdResponse$Outbound,
    z.ZodTypeDef,
    GetOrderByIdResponse
> = z
    .object({
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        order: Order$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            body: "Body",
            contentType: "ContentType",
            order: "Order",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdResponse$ {
    /** @deprecated use `GetOrderByIdResponse$inboundSchema` instead. */
    export const inboundSchema = GetOrderByIdResponse$inboundSchema;
    /** @deprecated use `GetOrderByIdResponse$outboundSchema` instead. */
    export const outboundSchema = GetOrderByIdResponse$outboundSchema;
    /** @deprecated use `GetOrderByIdResponse$Outbound` instead. */
    export type Outbound = GetOrderByIdResponse$Outbound;
}
