/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64";
import { Order, Order$ } from "./order";
import * as z from "zod";

export type GetOrderByIdRequest = {
    /**
     * ID of order that needs to be fetched
     */
    orderId: number;
};

export type GetOrderByIdResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    order?: Order | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetOrderByIdRequest$ {
    export const inboundSchema: z.ZodType<GetOrderByIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });

    export type Outbound = {
        orderId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrderByIdRequest> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });
}

/** @internal */
export namespace GetOrderByIdResponse$ {
    export const inboundSchema: z.ZodType<GetOrderByIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            Body: b64$.zodInbound.optional(),
            ContentType: z.string(),
            Order: Order$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.Body === undefined ? null : { body: v.Body }),
                contentType: v.ContentType,
                ...(v.Order === undefined ? null : { order: v.Order }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        Body?: Uint8Array | undefined;
        ContentType: string;
        Order?: Order$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrderByIdResponse> = z
        .object({
            body: b64$.zodOutbound.optional(),
            contentType: z.string(),
            order: Order$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.body === undefined ? null : { Body: v.body }),
                ContentType: v.contentType,
                ...(v.order === undefined ? null : { Order: v.order }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
