/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { Pet, Pet$inboundSchema, Pet$Outbound, Pet$outboundSchema } from "./pet.js";
import * as z from "zod";

export type GetPetByIdSecurity = {
    apiKey?: string | undefined;
    petstoreAuth?: string | undefined;
};

export type GetPetByIdRequest = {
    /**
     * ID of pet to return
     */
    petId: number;
};

export type GetPetByIdResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    pet?: Pet | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const GetPetByIdSecurity$inboundSchema: z.ZodType<
    GetPetByIdSecurity,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        api_key: z.string().optional(),
        petstore_auth: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            api_key: "apiKey",
            petstore_auth: "petstoreAuth",
        });
    });

/** @internal */
export type GetPetByIdSecurity$Outbound = {
    api_key?: string | undefined;
    petstore_auth?: string | undefined;
};

/** @internal */
export const GetPetByIdSecurity$outboundSchema: z.ZodType<
    GetPetByIdSecurity$Outbound,
    z.ZodTypeDef,
    GetPetByIdSecurity
> = z
    .object({
        apiKey: z.string().optional(),
        petstoreAuth: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            apiKey: "api_key",
            petstoreAuth: "petstore_auth",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPetByIdSecurity$ {
    /** @deprecated use `GetPetByIdSecurity$inboundSchema` instead. */
    export const inboundSchema = GetPetByIdSecurity$inboundSchema;
    /** @deprecated use `GetPetByIdSecurity$outboundSchema` instead. */
    export const outboundSchema = GetPetByIdSecurity$outboundSchema;
    /** @deprecated use `GetPetByIdSecurity$Outbound` instead. */
    export type Outbound = GetPetByIdSecurity$Outbound;
}

/** @internal */
export const GetPetByIdRequest$inboundSchema: z.ZodType<GetPetByIdRequest, z.ZodTypeDef, unknown> =
    z.object({
        petId: z.number().int(),
    });

/** @internal */
export type GetPetByIdRequest$Outbound = {
    petId: number;
};

/** @internal */
export const GetPetByIdRequest$outboundSchema: z.ZodType<
    GetPetByIdRequest$Outbound,
    z.ZodTypeDef,
    GetPetByIdRequest
> = z.object({
    petId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPetByIdRequest$ {
    /** @deprecated use `GetPetByIdRequest$inboundSchema` instead. */
    export const inboundSchema = GetPetByIdRequest$inboundSchema;
    /** @deprecated use `GetPetByIdRequest$outboundSchema` instead. */
    export const outboundSchema = GetPetByIdRequest$outboundSchema;
    /** @deprecated use `GetPetByIdRequest$Outbound` instead. */
    export type Outbound = GetPetByIdRequest$Outbound;
}

/** @internal */
export const GetPetByIdResponse$inboundSchema: z.ZodType<
    GetPetByIdResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        Pet: Pet$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            Body: "body",
            ContentType: "contentType",
            Pet: "pet",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetPetByIdResponse$Outbound = {
    Body?: Uint8Array | undefined;
    ContentType: string;
    Pet?: Pet$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const GetPetByIdResponse$outboundSchema: z.ZodType<
    GetPetByIdResponse$Outbound,
    z.ZodTypeDef,
    GetPetByIdResponse
> = z
    .object({
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        pet: Pet$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            body: "Body",
            contentType: "ContentType",
            pet: "Pet",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPetByIdResponse$ {
    /** @deprecated use `GetPetByIdResponse$inboundSchema` instead. */
    export const inboundSchema = GetPetByIdResponse$inboundSchema;
    /** @deprecated use `GetPetByIdResponse$outboundSchema` instead. */
    export const outboundSchema = GetPetByIdResponse$outboundSchema;
    /** @deprecated use `GetPetByIdResponse$Outbound` instead. */
    export type Outbound = GetPetByIdResponse$Outbound;
}
