/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64";
import { Pet, Pet$ } from "./pet";
import * as z from "zod";

export type GetPetByIdSecurity = {
    apiKey?: string | undefined;
    petstoreAuth?: string | undefined;
};

export type GetPetByIdRequest = {
    /**
     * ID of pet to return
     */
    petId: number;
};

export type GetPetByIdResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    pet?: Pet | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetPetByIdSecurity$ {
    export const inboundSchema: z.ZodType<GetPetByIdSecurity, z.ZodTypeDef, unknown> = z
        .object({
            api_key: z.string().optional(),
            petstore_auth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.api_key === undefined ? null : { apiKey: v.api_key }),
                ...(v.petstore_auth === undefined ? null : { petstoreAuth: v.petstore_auth }),
            };
        });

    export type Outbound = {
        api_key?: string | undefined;
        petstore_auth?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPetByIdSecurity> = z
        .object({
            apiKey: z.string().optional(),
            petstoreAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.apiKey === undefined ? null : { api_key: v.apiKey }),
                ...(v.petstoreAuth === undefined ? null : { petstore_auth: v.petstoreAuth }),
            };
        });
}

/** @internal */
export namespace GetPetByIdRequest$ {
    export const inboundSchema: z.ZodType<GetPetByIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            petId: z.number().int(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
            };
        });

    export type Outbound = {
        petId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPetByIdRequest> = z
        .object({
            petId: z.number().int(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
            };
        });
}

/** @internal */
export namespace GetPetByIdResponse$ {
    export const inboundSchema: z.ZodType<GetPetByIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            Body: b64$.zodInbound.optional(),
            ContentType: z.string(),
            Pet: Pet$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.Body === undefined ? null : { body: v.Body }),
                contentType: v.ContentType,
                ...(v.Pet === undefined ? null : { pet: v.Pet }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        Body?: Uint8Array | undefined;
        ContentType: string;
        Pet?: Pet$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPetByIdResponse> = z
        .object({
            body: b64$.zodOutbound.optional(),
            contentType: z.string(),
            pet: Pet$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.body === undefined ? null : { Body: v.body }),
                ContentType: v.contentType,
                ...(v.pet === undefined ? null : { Pet: v.pet }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
