/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { User, User$inboundSchema, User$Outbound, User$outboundSchema } from "./user.js";
import * as z from "zod";

export type GetUserByNameRequest = {
    /**
     * The name that needs to be fetched. Use user1 for testing.
     */
    username: string;
};

export type GetUserByNameResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * successful operation
     */
    user?: User | undefined;
};

/** @internal */
export const GetUserByNameRequest$inboundSchema: z.ZodType<
    GetUserByNameRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    username: z.string(),
});

/** @internal */
export type GetUserByNameRequest$Outbound = {
    username: string;
};

/** @internal */
export const GetUserByNameRequest$outboundSchema: z.ZodType<
    GetUserByNameRequest$Outbound,
    z.ZodTypeDef,
    GetUserByNameRequest
> = z.object({
    username: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserByNameRequest$ {
    /** @deprecated use `GetUserByNameRequest$inboundSchema` instead. */
    export const inboundSchema = GetUserByNameRequest$inboundSchema;
    /** @deprecated use `GetUserByNameRequest$outboundSchema` instead. */
    export const outboundSchema = GetUserByNameRequest$outboundSchema;
    /** @deprecated use `GetUserByNameRequest$Outbound` instead. */
    export type Outbound = GetUserByNameRequest$Outbound;
}

/** @internal */
export const GetUserByNameResponse$inboundSchema: z.ZodType<
    GetUserByNameResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        User: User$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            Body: "body",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
            User: "user",
        });
    });

/** @internal */
export type GetUserByNameResponse$Outbound = {
    Body?: Uint8Array | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    User?: User$Outbound | undefined;
};

/** @internal */
export const GetUserByNameResponse$outboundSchema: z.ZodType<
    GetUserByNameResponse$Outbound,
    z.ZodTypeDef,
    GetUserByNameResponse
> = z
    .object({
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        user: User$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            body: "Body",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
            user: "User",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserByNameResponse$ {
    /** @deprecated use `GetUserByNameResponse$inboundSchema` instead. */
    export const inboundSchema = GetUserByNameResponse$inboundSchema;
    /** @deprecated use `GetUserByNameResponse$outboundSchema` instead. */
    export const outboundSchema = GetUserByNameResponse$outboundSchema;
    /** @deprecated use `GetUserByNameResponse$Outbound` instead. */
    export type Outbound = GetUserByNameResponse$Outbound;
}
