/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type LoginUserRequest = {
    /**
     * The user name for login
     */
    username?: string | undefined;
    /**
     * The password for login in clear text
     */
    password?: string | undefined;
};

export type LoginUserResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: { [k: string]: Array<string> };
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * successful operation
     */
    res?: string | undefined;
    /**
     * successful operation
     */
    string?: string | undefined;
};

/** @internal */
export const LoginUserRequest$inboundSchema: z.ZodType<LoginUserRequest, z.ZodTypeDef, unknown> =
    z.object({
        username: z.string().optional(),
        password: z.string().optional(),
    });

/** @internal */
export type LoginUserRequest$Outbound = {
    username?: string | undefined;
    password?: string | undefined;
};

/** @internal */
export const LoginUserRequest$outboundSchema: z.ZodType<
    LoginUserRequest$Outbound,
    z.ZodTypeDef,
    LoginUserRequest
> = z.object({
    username: z.string().optional(),
    password: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginUserRequest$ {
    /** @deprecated use `LoginUserRequest$inboundSchema` instead. */
    export const inboundSchema = LoginUserRequest$inboundSchema;
    /** @deprecated use `LoginUserRequest$outboundSchema` instead. */
    export const outboundSchema = LoginUserRequest$outboundSchema;
    /** @deprecated use `LoginUserRequest$Outbound` instead. */
    export type Outbound = LoginUserRequest$Outbound;
}

/** @internal */
export const LoginUserResponse$inboundSchema: z.ZodType<LoginUserResponse, z.ZodTypeDef, unknown> =
    z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            res: z.string().optional(),
            string: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                Headers: "headers",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

/** @internal */
export type LoginUserResponse$Outbound = {
    ContentType: string;
    Headers: { [k: string]: Array<string> };
    StatusCode: number;
    RawResponse: never;
    res?: string | undefined;
    string?: string | undefined;
};

/** @internal */
export const LoginUserResponse$outboundSchema: z.ZodType<
    LoginUserResponse$Outbound,
    z.ZodTypeDef,
    LoginUserResponse
> = z
    .object({
        contentType: z.string(),
        headers: z.record(z.array(z.string())),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        res: z.string().optional(),
        string: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            headers: "Headers",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginUserResponse$ {
    /** @deprecated use `LoginUserResponse$inboundSchema` instead. */
    export const inboundSchema = LoginUserResponse$inboundSchema;
    /** @deprecated use `LoginUserResponse$outboundSchema` instead. */
    export const outboundSchema = LoginUserResponse$outboundSchema;
    /** @deprecated use `LoginUserResponse$Outbound` instead. */
    export type Outbound = LoginUserResponse$Outbound;
}
