/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    Category,
    Category$inboundSchema,
    Category$Outbound,
    Category$outboundSchema,
} from "./category.js";
import { Tag, Tag$inboundSchema, Tag$Outbound, Tag$outboundSchema } from "./tag.js";
import * as z from "zod";

/**
 * pet status in the store
 */
export enum PetStatus {
    Available = "available",
    Pending = "pending",
    Sold = "sold",
}

export type Pet = {
    category?: Category | undefined;
    id?: number | undefined;
    name: string;
    photoUrls: Array<string>;
    /**
     * pet status in the store
     */
    status?: PetStatus | undefined;
    tags?: Array<Tag> | undefined;
};

/** @internal */
export const PetStatus$inboundSchema: z.ZodNativeEnum<typeof PetStatus> = z.nativeEnum(PetStatus);

/** @internal */
export const PetStatus$outboundSchema: z.ZodNativeEnum<typeof PetStatus> = PetStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PetStatus$ {
    /** @deprecated use `PetStatus$inboundSchema` instead. */
    export const inboundSchema = PetStatus$inboundSchema;
    /** @deprecated use `PetStatus$outboundSchema` instead. */
    export const outboundSchema = PetStatus$outboundSchema;
}

/** @internal */
export const Pet$inboundSchema: z.ZodType<Pet, z.ZodTypeDef, unknown> = z.object({
    category: Category$inboundSchema.optional(),
    id: z.number().int().optional(),
    name: z.string(),
    photoUrls: z.array(z.string()),
    status: PetStatus$inboundSchema.optional(),
    tags: z.array(Tag$inboundSchema).optional(),
});

/** @internal */
export type Pet$Outbound = {
    category?: Category$Outbound | undefined;
    id?: number | undefined;
    name: string;
    photoUrls: Array<string>;
    status?: string | undefined;
    tags?: Array<Tag$Outbound> | undefined;
};

/** @internal */
export const Pet$outboundSchema: z.ZodType<Pet$Outbound, z.ZodTypeDef, Pet> = z.object({
    category: Category$outboundSchema.optional(),
    id: z.number().int().optional(),
    name: z.string(),
    photoUrls: z.array(z.string()),
    status: PetStatus$outboundSchema.optional(),
    tags: z.array(Tag$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Pet$ {
    /** @deprecated use `Pet$inboundSchema` instead. */
    export const inboundSchema = Pet$inboundSchema;
    /** @deprecated use `Pet$outboundSchema` instead. */
    export const outboundSchema = Pet$outboundSchema;
    /** @deprecated use `Pet$Outbound` instead. */
    export type Outbound = Pet$Outbound;
}
