/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Order, Order$ } from "./order";
import * as z from "zod";

export type PlaceOrderJsonResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    order?: Order | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace PlaceOrderJsonResponse$ {
    export const inboundSchema: z.ZodType<PlaceOrderJsonResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Order: Order$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Order === undefined ? null : { order: v.Order }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Order?: Order$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PlaceOrderJsonResponse> = z
        .object({
            contentType: z.string(),
            order: Order$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.order === undefined ? null : { Order: v.order }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
