/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import { Order, Order$inboundSchema, Order$Outbound, Order$outboundSchema } from "./order.js";
import * as z from "zod";

export type PlaceOrderJsonResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    order?: Order | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const PlaceOrderJsonResponse$inboundSchema: z.ZodType<
    PlaceOrderJsonResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        Order: Order$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            Order: "order",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type PlaceOrderJsonResponse$Outbound = {
    ContentType: string;
    Order?: Order$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const PlaceOrderJsonResponse$outboundSchema: z.ZodType<
    PlaceOrderJsonResponse$Outbound,
    z.ZodTypeDef,
    PlaceOrderJsonResponse
> = z
    .object({
        contentType: z.string(),
        order: Order$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            order: "Order",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlaceOrderJsonResponse$ {
    /** @deprecated use `PlaceOrderJsonResponse$inboundSchema` instead. */
    export const inboundSchema = PlaceOrderJsonResponse$inboundSchema;
    /** @deprecated use `PlaceOrderJsonResponse$outboundSchema` instead. */
    export const outboundSchema = PlaceOrderJsonResponse$outboundSchema;
    /** @deprecated use `PlaceOrderJsonResponse$Outbound` instead. */
    export type Outbound = PlaceOrderJsonResponse$Outbound;
}
