/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import { Order, Order$inboundSchema, Order$Outbound, Order$outboundSchema } from "./order.js";
import * as z from "zod";

export type PlaceOrderRawResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * successful operation
     */
    order?: Order | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const PlaceOrderRawResponse$inboundSchema: z.ZodType<
    PlaceOrderRawResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        Order: Order$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            Order: "order",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type PlaceOrderRawResponse$Outbound = {
    ContentType: string;
    Order?: Order$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const PlaceOrderRawResponse$outboundSchema: z.ZodType<
    PlaceOrderRawResponse$Outbound,
    z.ZodTypeDef,
    PlaceOrderRawResponse
> = z
    .object({
        contentType: z.string(),
        order: Order$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            order: "Order",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlaceOrderRawResponse$ {
    /** @deprecated use `PlaceOrderRawResponse$inboundSchema` instead. */
    export const inboundSchema = PlaceOrderRawResponse$inboundSchema;
    /** @deprecated use `PlaceOrderRawResponse$outboundSchema` instead. */
    export const outboundSchema = PlaceOrderRawResponse$outboundSchema;
    /** @deprecated use `PlaceOrderRawResponse$Outbound` instead. */
    export type Outbound = PlaceOrderRawResponse$Outbound;
}
