/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    petstoreAuth?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
        .object({
            petstore_auth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.petstore_auth === undefined ? null : { petstoreAuth: v.petstore_auth }),
            };
        });

    export type Outbound = {
        petstore_auth?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            petstoreAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.petstoreAuth === undefined ? null : { petstore_auth: v.petstoreAuth }),
            };
        });
}
