/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import { User, User$inboundSchema, User$Outbound, User$outboundSchema } from "./user.js";
import * as z from "zod";

export type UpdateUserJsonRequest = {
    /**
     * name that needs to be updated
     */
    username: string;
    /**
     * Update an existent user in the store
     */
    user?: User | undefined;
};

export type UpdateUserJsonResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UpdateUserJsonRequest$inboundSchema: z.ZodType<
    UpdateUserJsonRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        username: z.string(),
        User: User$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            User: "user",
        });
    });

/** @internal */
export type UpdateUserJsonRequest$Outbound = {
    username: string;
    User?: User$Outbound | undefined;
};

/** @internal */
export const UpdateUserJsonRequest$outboundSchema: z.ZodType<
    UpdateUserJsonRequest$Outbound,
    z.ZodTypeDef,
    UpdateUserJsonRequest
> = z
    .object({
        username: z.string(),
        user: User$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            user: "User",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserJsonRequest$ {
    /** @deprecated use `UpdateUserJsonRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateUserJsonRequest$inboundSchema;
    /** @deprecated use `UpdateUserJsonRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateUserJsonRequest$outboundSchema;
    /** @deprecated use `UpdateUserJsonRequest$Outbound` instead. */
    export type Outbound = UpdateUserJsonRequest$Outbound;
}

/** @internal */
export const UpdateUserJsonResponse$inboundSchema: z.ZodType<
    UpdateUserJsonResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UpdateUserJsonResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UpdateUserJsonResponse$outboundSchema: z.ZodType<
    UpdateUserJsonResponse$Outbound,
    z.ZodTypeDef,
    UpdateUserJsonResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserJsonResponse$ {
    /** @deprecated use `UpdateUserJsonResponse$inboundSchema` instead. */
    export const inboundSchema = UpdateUserJsonResponse$inboundSchema;
    /** @deprecated use `UpdateUserJsonResponse$outboundSchema` instead. */
    export const outboundSchema = UpdateUserJsonResponse$outboundSchema;
    /** @deprecated use `UpdateUserJsonResponse$Outbound` instead. */
    export type Outbound = UpdateUserJsonResponse$Outbound;
}
