/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type UpdatePetWithFormRequest = {
    /**
     * ID of pet that needs to be updated
     */
    petId: number;
    /**
     * Name of pet that needs to be updated
     */
    name?: string | undefined;
    /**
     * Status of pet that needs to be updated
     */
    status?: string | undefined;
};

export type UpdatePetWithFormResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UpdatePetWithFormRequest$inboundSchema: z.ZodType<
    UpdatePetWithFormRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    petId: z.number().int(),
    name: z.string().optional(),
    status: z.string().optional(),
});

/** @internal */
export type UpdatePetWithFormRequest$Outbound = {
    petId: number;
    name?: string | undefined;
    status?: string | undefined;
};

/** @internal */
export const UpdatePetWithFormRequest$outboundSchema: z.ZodType<
    UpdatePetWithFormRequest$Outbound,
    z.ZodTypeDef,
    UpdatePetWithFormRequest
> = z.object({
    petId: z.number().int(),
    name: z.string().optional(),
    status: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetWithFormRequest$ {
    /** @deprecated use `UpdatePetWithFormRequest$inboundSchema` instead. */
    export const inboundSchema = UpdatePetWithFormRequest$inboundSchema;
    /** @deprecated use `UpdatePetWithFormRequest$outboundSchema` instead. */
    export const outboundSchema = UpdatePetWithFormRequest$outboundSchema;
    /** @deprecated use `UpdatePetWithFormRequest$Outbound` instead. */
    export type Outbound = UpdatePetWithFormRequest$Outbound;
}

/** @internal */
export const UpdatePetWithFormResponse$inboundSchema: z.ZodType<
    UpdatePetWithFormResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UpdatePetWithFormResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UpdatePetWithFormResponse$outboundSchema: z.ZodType<
    UpdatePetWithFormResponse$Outbound,
    z.ZodTypeDef,
    UpdatePetWithFormResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetWithFormResponse$ {
    /** @deprecated use `UpdatePetWithFormResponse$inboundSchema` instead. */
    export const inboundSchema = UpdatePetWithFormResponse$inboundSchema;
    /** @deprecated use `UpdatePetWithFormResponse$outboundSchema` instead. */
    export const outboundSchema = UpdatePetWithFormResponse$outboundSchema;
    /** @deprecated use `UpdatePetWithFormResponse$Outbound` instead. */
    export type Outbound = UpdatePetWithFormResponse$Outbound;
}
