/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

export type UpdateUserRawRequest = {
    /**
     * name that needs to be updated
     */
    username: string;
    /**
     * Update an existent user in the store
     */
    requestBody?: Uint8Array | string | undefined;
};

export type UpdateUserRawResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UpdateUserRawRequest$inboundSchema: z.ZodType<
    UpdateUserRawRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        username: z.string(),
        RequestBody: b64$.zodInbound.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type UpdateUserRawRequest$Outbound = {
    username: string;
    RequestBody?: Uint8Array | undefined;
};

/** @internal */
export const UpdateUserRawRequest$outboundSchema: z.ZodType<
    UpdateUserRawRequest$Outbound,
    z.ZodTypeDef,
    UpdateUserRawRequest
> = z
    .object({
        username: z.string(),
        requestBody: b64$.zodOutbound.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserRawRequest$ {
    /** @deprecated use `UpdateUserRawRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateUserRawRequest$inboundSchema;
    /** @deprecated use `UpdateUserRawRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateUserRawRequest$outboundSchema;
    /** @deprecated use `UpdateUserRawRequest$Outbound` instead. */
    export type Outbound = UpdateUserRawRequest$Outbound;
}

/** @internal */
export const UpdateUserRawResponse$inboundSchema: z.ZodType<
    UpdateUserRawResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UpdateUserRawResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UpdateUserRawResponse$outboundSchema: z.ZodType<
    UpdateUserRawResponse$Outbound,
    z.ZodTypeDef,
    UpdateUserRawResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserRawResponse$ {
    /** @deprecated use `UpdateUserRawResponse$inboundSchema` instead. */
    export const inboundSchema = UpdateUserRawResponse$inboundSchema;
    /** @deprecated use `UpdateUserRawResponse$outboundSchema` instead. */
    export const outboundSchema = UpdateUserRawResponse$outboundSchema;
    /** @deprecated use `UpdateUserRawResponse$Outbound` instead. */
    export type Outbound = UpdateUserRawResponse$Outbound;
}
