/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import { User, User$inboundSchema, User$Outbound, User$outboundSchema } from "./user.js";
import * as z from "zod";

export type UpdateUserFormRequest = {
    /**
     * name that needs to be updated
     */
    username: string;
    /**
     * Update an existent user in the store
     */
    user?: User | undefined;
};

export type UpdateUserFormResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UpdateUserFormRequest$inboundSchema: z.ZodType<
    UpdateUserFormRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        username: z.string(),
        User: User$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            User: "user",
        });
    });

/** @internal */
export type UpdateUserFormRequest$Outbound = {
    username: string;
    User?: User$Outbound | undefined;
};

/** @internal */
export const UpdateUserFormRequest$outboundSchema: z.ZodType<
    UpdateUserFormRequest$Outbound,
    z.ZodTypeDef,
    UpdateUserFormRequest
> = z
    .object({
        username: z.string(),
        user: User$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            user: "User",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserFormRequest$ {
    /** @deprecated use `UpdateUserFormRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateUserFormRequest$inboundSchema;
    /** @deprecated use `UpdateUserFormRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateUserFormRequest$outboundSchema;
    /** @deprecated use `UpdateUserFormRequest$Outbound` instead. */
    export type Outbound = UpdateUserFormRequest$Outbound;
}

/** @internal */
export const UpdateUserFormResponse$inboundSchema: z.ZodType<
    UpdateUserFormResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UpdateUserFormResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UpdateUserFormResponse$outboundSchema: z.ZodType<
    UpdateUserFormResponse$Outbound,
    z.ZodTypeDef,
    UpdateUserFormResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserFormResponse$ {
    /** @deprecated use `UpdateUserFormResponse$inboundSchema` instead. */
    export const inboundSchema = UpdateUserFormResponse$inboundSchema;
    /** @deprecated use `UpdateUserFormResponse$outboundSchema` instead. */
    export const outboundSchema = UpdateUserFormResponse$outboundSchema;
    /** @deprecated use `UpdateUserFormResponse$Outbound` instead. */
    export type Outbound = UpdateUserFormResponse$Outbound;
}
