/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdatePetWithFormRequest = {
    /**
     * ID of pet that needs to be updated
     */
    petId: number;
    /**
     * Name of pet that needs to be updated
     */
    name?: string | undefined;
    /**
     * Status of pet that needs to be updated
     */
    status?: string | undefined;
};

export type UpdatePetWithFormResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace UpdatePetWithFormRequest$ {
    export const inboundSchema: z.ZodType<UpdatePetWithFormRequest, z.ZodTypeDef, unknown> = z
        .object({
            petId: z.number().int(),
            name: z.string().optional(),
            status: z.string().optional(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });

    export type Outbound = {
        petId: number;
        name?: string | undefined;
        status?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdatePetWithFormRequest> = z
        .object({
            petId: z.number().int(),
            name: z.string().optional(),
            status: z.string().optional(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });
}

/** @internal */
export namespace UpdatePetWithFormResponse$ {
    export const inboundSchema: z.ZodType<UpdatePetWithFormResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdatePetWithFormResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
