/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import { Pet, Pet$inboundSchema, Pet$Outbound, Pet$outboundSchema } from "./pet.js";
import * as z from "zod";

export type UpdatePetJsonResponse = {
    body?: Uint8Array | string | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Successful operation
     */
    pet?: Pet | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UpdatePetJsonResponse$inboundSchema: z.ZodType<
    UpdatePetJsonResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Body: b64$.zodInbound.optional(),
        ContentType: z.string(),
        Pet: Pet$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            Body: "body",
            ContentType: "contentType",
            Pet: "pet",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UpdatePetJsonResponse$Outbound = {
    Body?: Uint8Array | undefined;
    ContentType: string;
    Pet?: Pet$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UpdatePetJsonResponse$outboundSchema: z.ZodType<
    UpdatePetJsonResponse$Outbound,
    z.ZodTypeDef,
    UpdatePetJsonResponse
> = z
    .object({
        body: b64$.zodOutbound.optional(),
        contentType: z.string(),
        pet: Pet$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            body: "Body",
            contentType: "ContentType",
            pet: "Pet",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetJsonResponse$ {
    /** @deprecated use `UpdatePetJsonResponse$inboundSchema` instead. */
    export const inboundSchema = UpdatePetJsonResponse$inboundSchema;
    /** @deprecated use `UpdatePetJsonResponse$outboundSchema` instead. */
    export const outboundSchema = UpdatePetJsonResponse$outboundSchema;
    /** @deprecated use `UpdatePetJsonResponse$Outbound` instead. */
    export type Outbound = UpdatePetJsonResponse$Outbound;
}
