/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../lib/base64.js";
import { remap as remap$ } from "../lib/primitives.js";
import {
    ApiResponse,
    ApiResponse$inboundSchema,
    ApiResponse$Outbound,
    ApiResponse$outboundSchema,
} from "./apiresponse.js";
import * as z from "zod";

export type UploadFileRequest = {
    /**
     * ID of pet to update
     */
    petId: number;
    /**
     * Additional Metadata
     */
    additionalMetadata?: string | undefined;
    requestBody?: Uint8Array | string | undefined;
};

export type UploadFileResponse = {
    /**
     * successful operation
     */
    apiResponse?: ApiResponse | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const UploadFileRequest$inboundSchema: z.ZodType<UploadFileRequest, z.ZodTypeDef, unknown> =
    z
        .object({
            petId: z.number().int(),
            additionalMetadata: z.string().optional(),
            RequestBody: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                RequestBody: "requestBody",
            });
        });

/** @internal */
export type UploadFileRequest$Outbound = {
    petId: number;
    additionalMetadata?: string | undefined;
    RequestBody?: Uint8Array | undefined;
};

/** @internal */
export const UploadFileRequest$outboundSchema: z.ZodType<
    UploadFileRequest$Outbound,
    z.ZodTypeDef,
    UploadFileRequest
> = z
    .object({
        petId: z.number().int(),
        additionalMetadata: z.string().optional(),
        requestBody: b64$.zodOutbound.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadFileRequest$ {
    /** @deprecated use `UploadFileRequest$inboundSchema` instead. */
    export const inboundSchema = UploadFileRequest$inboundSchema;
    /** @deprecated use `UploadFileRequest$outboundSchema` instead. */
    export const outboundSchema = UploadFileRequest$outboundSchema;
    /** @deprecated use `UploadFileRequest$Outbound` instead. */
    export type Outbound = UploadFileRequest$Outbound;
}

/** @internal */
export const UploadFileResponse$inboundSchema: z.ZodType<
    UploadFileResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ApiResponse: ApiResponse$inboundSchema.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ApiResponse: "apiResponse",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type UploadFileResponse$Outbound = {
    ApiResponse?: ApiResponse$Outbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const UploadFileResponse$outboundSchema: z.ZodType<
    UploadFileResponse$Outbound,
    z.ZodTypeDef,
    UploadFileResponse
> = z
    .object({
        apiResponse: ApiResponse$outboundSchema.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            apiResponse: "ApiResponse",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadFileResponse$ {
    /** @deprecated use `UploadFileResponse$inboundSchema` instead. */
    export const inboundSchema = UploadFileResponse$inboundSchema;
    /** @deprecated use `UploadFileResponse$outboundSchema` instead. */
    export const outboundSchema = UploadFileResponse$outboundSchema;
    /** @deprecated use `UploadFileResponse$Outbound` instead. */
    export type Outbound = UploadFileResponse$Outbound;
}
